package com.testproject.model;
// Generated Feb 22, 2020 2:17:55 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Account generated by hbm2java
 */
public class Account  implements java.io.Serializable {

    
     private int id;
     private Customer customer;
     private int accNumber;
     private String description;
     private Set<FinTransaction> finTransactions = new HashSet<FinTransaction>(0);

    public Account() {
    }

	
    public Account(int id, Customer customer, int accNumber, String description) {
        this.id = id;
        this.customer = customer;
        this.accNumber = accNumber;
        this.description = description;
    }
    public Account(int id, Customer customer, int accNumber, String description, Set<FinTransaction> finTransactions) {
       this.id = id;
       this.customer = customer;
       this.accNumber = accNumber;
       this.description = description;
       this.finTransactions = finTransactions;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public int getAccNumber() {
        return this.accNumber;
    }
    
    public void setAccNumber(int accNumber) {
        this.accNumber = accNumber;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set<FinTransaction> getFinTransactions() {
        return this.finTransactions;
    }
    
    public void setFinTransactions(Set<FinTransaction> finTransactions) {
        this.finTransactions = finTransactions;
    }




}


