package com.testproject.model;
// Generated Feb 22, 2020 2:17:55 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * FinTransaction generated by hbm2java
 */
public class FinTransaction  implements java.io.Serializable {


     private int id;
     private Account account;
     private Date dateTime;
     private int amount;
     private String description;

    public FinTransaction() {
    }

    public FinTransaction(int id, Account account, Date dateTime, int amount, String description) {
       this.id = id;
       this.account = account;
       this.dateTime = dateTime;
       this.amount = amount;
       this.description = description;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Account getAccount() {
        return this.account;
    }
    
    public void setAccount(Account account) {
        this.account = account;
    }
    public Date getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }
    public int getAmount() {
        return this.amount;
    }
    
    public void setAmount(int amount) {
        this.amount = amount;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


